version: '3.8'

services:
  fastapi:
    build: ./fast_app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DATABASE_NAME=global_terrorism_db
    networks:
      - app_network  

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"  
    networks:
      - app_network 

networks:
  app_network:  
    driver: bridge